services:
  mongodb:
    image: mongo:7
    container_name: bullrush-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

  redis:
    image: redis:7-alpine
    container_name: bullrush-redis
    ports:
      - "6379:6379"

volumes:
  mongodata:
